name: Unit and e2e Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: windows-latest
    # concurrency:
    #   group: testing
    #   cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/workflows/test-setup

      - name: Run unit tests
      # see microsoft API for reference on the difference between & and &&: 
      # https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.5&viewFallbackFrom=powershell-7.1#call-operator-
      # - oli
        run: |
          .\resources\config-neo4j.ps1 &
          sleep 10 && 
          npm run test:unit -- -- --run
          
  e2e-test:
    runs-on: windows-latest
    # concurrency:
    #   group: testing
    #   cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/workflows/test-setup

      - name: Run e2e requirements tests 
        run: | 
          .\resources\config-neo4j.ps1 &
          sleep 10 && npm run test:e2e:driver
          npm run test:e2e -- -- --run

      - name: Run e2e bench/NFR tests
        run: |
          .\resources\config-neo4j.ps1 &
          sleep 10 && 
          npm run test:e2e:driver 
          npm run test:e2e:bench -- -- --run

# - name: Configure Neo4j
    #   run: .\resources\config-neo4j.ps1
    #   shell: pwsh