name: Unit and e2e Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: windows-latest
    steps:
      - name: Set up environment
        uses: ./.github/workflows/test-setup

      - name: Run unit tests
        run: npm run test:unit -- -- --run
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/workflows/test-setup

      - name: Run e2e requirements tests
        run: | 
          npm run test:e2e:driver &
          sleep 10 &&
          npm run test:e2e -- -- --run
          
      - name: Run e2e bench/NFR tests
        run: | 
          npm run test:e2e:driver &
          sleep 10 &&
          npm run test:e2e:bench -- -- --run
